apiVersion: v1
data:
  LIBRENMS_CRON_ALERTS_ENABLE: "true"
  LIBRENMS_CRON_BILLING_CALCULATE_ENABLE: "true"
  LIBRENMS_CRON_BILLING_ENABLE: "true"
  LIBRENMS_CRON_CHECK_SERVICES_ENABLE: "true"
  LIBRENMS_CRON_DAILY_ENABLE: "true"
  LIBRENMS_CRON_DISCOVERY_ENABLE: "true"
  LIBRENMS_CRON_POLLER_ENABLE: "true"
  LIBRENMS_POLLER_INTERVAL: "5"
  LIBRENMS_POLLER_THREADS: "16"
  LIBRENMS_SNMP_COMMUNITY: librenmsdocker
  MEMCACHED_HOST: memcached
  MEMCACHED_PORT: "11211"
  MEMORY_LIMIT: 256M
  OPCACHE_MEM_SIZE: "128"
  RRDCACHED_HOST: rrdcached
  RRDCACHED_PORT: "42217"
  UPLOAD_MAX_SIZE: 16M
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: syslog-ng-librenms-env
  name: syslog-ng-librenms-env
