apiVersion: v1
data:
  LIBRENMS_CRON_ALERTS_ENABLE: "true"
  LIBRENMS_CRON_BILLING_CALCULATE_ENABLE: "true"
  LIBRENMS_CRON_BILLING_ENABLE: "true"
  LIBRENMS_CRON_CHECK_SERVICES_ENABLE: "true"
  LIBRENMS_CRON_DAILY_ENABLE: "true"
  LIBRENMS_CRON_DISCOVERY_ENABLE: "true"
  LIBRENMS_CRON_POLLER_ENABLE: "true"
  LIBRENMS_POLLER_INTERVAL: "5"
  LIBRENMS_POLLER_THREADS: "16"
  LIBRENMS_SNMP_COMMUNITY: librenmsdocker
  MEMCACHED_HOST: memcached.librenms.svc.cluster.local
  MEMCACHED_PORT: "11211"
  MEMORY_LIMIT: 256M
  OPCACHE_MEM_SIZE: "128"
  RRDCACHED_HOST: rrdcached.librenms.svc.cluster.local
  RRDCACHED_PORT: "42217"
  UPLOAD_MAX_SIZE: 16M
  DOMAINNAME: example.com
  HOSTNAME: librenms
  MYSQL_DATABASE: librenms
  MYSQL_USER: librenms
  MYSQL_PASSWORD: librenms
  SMTP_SERVER: smtp.example.com
  SMTP_USERNAME: smtp@example.com
  SMTP_PASSWORD:
  TZ: UTC

kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: app-librenms-env
  name: app-librenms-env
